### ISSUE TITLE
🐛 [BUG] - Elasticsearch query being overwritten

### ISSUE THREAD

**Issue by rahusinh** [google/slo-generator#309]
### SLO Generator Version

v2.3.3

### Python Version

3.9.6

### What happened?

When using the elasticsearch backend, any query that doesn't contain "filter" gets overwritten.

Example query in configuration : 
```
query_bad:
  must:
    term:
      name: JAgOZE8
```
This query will be overwritten because the following section in ```slo_generator/backends/elasticsearch.py```:

the query is assigned (line 151):
```
body = {"query": {"bool": query}, "track_total_hits": True}
```

Then it is overwritten (line 164):
```
if "filter" in body["query"]["bool"]:
    body["query"]["bool"]["filter"]["range"] = range_query
else:
    body["query"]["bool"] = {"filter": {"range": range_query}}
```

I believe it should be:
```
if "filter" in body["query"]["bool"]:
    body["query"]["bool"]["filter"]["range"] = range_query
else:
    body["query"]["bool"]["filter"] = {"range": range_query}
```

### What did you expect?

The inserted query through the slo config yaml should reflect in the elasticsearch query. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lvaylet** [comment]
Hi @rahusinh and thanks for raising this issue.

I am back from vacation and will take a look at it over the next few days. Thanks for your patience!

**Comment by lvaylet** [comment]
Hi @rahusinh, I was able to confirm earlier today that the code does not behave as expected. It overwrites the whole `filter` clause while it should only add or update a single field.

I am not able to accept your PR as it does not include any test for the new behavior. However, to thank you for your patience, I went ahead and created #312 with your change and new unit tests. Can you take a look and confirm this is the expected behavior?

**Comment by rahusinh** [comment]
Hi @lvaylet, I apologize for not adding the test. I tested it out and yes, that is the expected behavior. Thanks!

**Comment by lvaylet** [comment]
Amazing, thank you. I will go ahead and merge my PR.
